### ISSUE TITLE
davlik objects to be implemented + their classes

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#10]
Object
- equals
- hashCode
- toString

String
- value
- count
- offset
- hashCode

When used for object references, registers are considered wide enough to hold exactly one such reference.
In terms of bitwise representation, (Object) null == (int) 0.

**Comment by jjfiv** [comment]
Started this; see src/native.js

Also, I think that references should be stored "as-is", rather than manufacturing pointers. It will give us the benefit of using javascripts garbage collector.

e.g. making a new "String" will actually put a string in the register. OR it will put in a wrapper object. See the issue about making an instance format.

**Comment by etosch** [comment]
So what's the goal here?

**Comment by jjfiv** [comment]
The goal here is that when we load up the standard library, some methods will be missing. This is a little bit down the road, but we will need javascript-based "native" functions to handle some core things. The most basic one will be: `LPrintStream;.println`

**Comment by jjfiv** [comment]
This will be dealt with piecewise. Closing for now.
