### ISSUE TITLE
vmtest/index.html not working

### ISSUE THREAD

**Issue by VJD215** [jjfiv/dalvik-js#106]
When I run the vmtest/index.html file I'm getting a ReferenceError: isA is not defined, this is pointing to util.js (  if(isA(obj, 'Thread')){ return obj.uid+":"+obj.state;}. any thoughts?

**Comment by etosch** [comment]
If you poke around on the wiki, you'll find a page that has some grep
tricks. I'd suggest using those to find which files call isA.

How do each of our javascript files "see" each other?  If you look at the
top of each .js file, you'll notice that we've manually entered the
dependencies. There are no calls to use namespaces or import libraries;
instead, all that linking type stuff happens in the browser. Take a look at
the html file you're using; I've found that 90% of the time, when there's a
reference error at runtime,  it's because the javascript file hasn't been
entered into the list of things to load. The other 10% of the time it's
because there's an error in that file that causes its load to fail silently
(e.g. improperly balanced curly braces).

On Wed, Oct 31, 2012 at 11:22 AM, VJD215 notifications@github.com wrote:

> When I run the vmtest/index.html file I'm getting a ReferenceError: isA is
> not defined, this is pointing to util.js ( if(isA(obj, 'Thread')){ return
> obj.uid+":"+obj.state;}. any thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/106.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
Probably need to include a file in vmtest/index.html; if src/index.html works that means that that file is properly included in src/index.html

**Comment by VJD215** [comment]
missing two files and an update was pushed
