### ISSUE TITLE
register width and alignment

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#11]
"When used for bit values (such as integers and floating point numbers), registers are considered 32 bits wide. Adjacent register pairs are used for 64-bit values. There is no alignment requirement for register pairs."

**Comment by jjfiv** [comment]
Javascript "Numbers" hold roughly 56 bits.

**Comment by etosch** [comment]
So how are we enforcing this again? Also, where is it handled?

**Comment by jjfiv** [comment]
I'm going to go looking for the Google "long" library. It is not handled anywhere yet. I imagine that we will use the Type object to do some of this.

We will need to have a function that takes a value and a type and makes sure the value is within the proper bounds for the given type.

**Comment by jjfiv** [comment]
File added as [gLong.js](https://github.com/jjfiv/dalvik-js/blob/master/src/gLong.js#L808), slightly modified from original.

Note that:
`gLong.fromNumber(10).add(7) === 10` because their operations expect both operands to be gLong objects. This is rather annoying.

Need to do:
`gLong.fromNumber(10).add(gLong.fromNumber(7)) === 17`

**Comment by jjfiv** [comment]
We're going to ignore register pairs for now, indefinitely not supporting code that depends on the ordering of partial data in registers.
