### ISSUE TITLE
question????

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#12]
"The storage unit in the instruction stream is a 16-bit unsigned quantity. Some bits in some instructions are ignored / must-be-zero."

What does this mean?

**Comment by jjfiv** [comment]
This is a way of having reserved fields. Basically, the bits within an instruction mean something; once in a while, there are pieces of the binary field that aren't used. Specifications often go back and forth between what "must be zero" and what is "ignored", because the parser doesn't actually read it.

That being said, I haven't noticed any "reserved" chunks of instructions. They seem to be straightforward.

**Comment by etosch** [comment]
Okay, so should I close this? I just wanted to post pieces of the specs, one by one, to make sure we touch everything.
