### ISSUE TITLE
object constructor convenction

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#23]
Request for an addendum to the commandments: when defining an object class constructor, can we make that aspect clear by defining like this:

function Type(args){
}

rather than

var Type = function (args){
}

While it's clear that objects are capitalized, I think it would enhance readability to have a clear distinction between expected behavior of the base "class" and the "extras" we add via the whole prototype shebang.

**Comment by jjfiv** [comment]
Makes no difference to me; I was just using that form so that all 
functions are defined the same way / it's also the only way to properly 
scope functions:

function Type() //goes in global scope always.
var Type = function() { } // goes in enclosing scope because var

We're just polluting the global namespace with our classes so it really 
doesn't matter. Go ahead and update them all, if you like.

**Comment by etosch** [comment]
Nope, that's fine. If it ain't broke, why fix it?
