### ISSUE TITLE
documentation of major steps

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#29]
How does you system work?
- start from index.html
- Choose a dex file
- Hit load
  This starts the process rooted controlled entirely in Upload.js. Upload.js handles interaction between the browser and the VM. When the user clicks on the "Load File" button, this kicks off a process that parses the input file, loads up the VM with the appropriate number of threads, and does something at then end of its lifetime.
- Can support multiple files loaded in? I noticed that the file upload returns an array. I created a task for this in Issue #26.
- "onClickLoad" looks like it assigns the appropriate bindings to the function fileReady, which is...a callback?...attached to the FileReaderObject that calls "onFileReady" as its last step.
- "onFileReady" creates an ArrayFile (this looks like it's mostly just an indexing of offsets - any more to know about it?) that is fed as data into the DEXData object, which is located in dexLoader. This parses everything. Where do we actually launch execution?

**Comment by jjfiv** [comment]
Right now, there are two html files:
- `index.html` This file is used to test the dexLoader and icodeGen modules. It is not yet connected to the VM, because these modules are not complete enough.
- `mock-hello.html` This file is used to run the VM on the handcrafted `mock-hello.js`, which is what the output of dexLoader/icodeGen should look like.

Basically, the whole pipeline is what we'd get if we jammed the two pieces together.

Steps to run `index.html`
1. Open index.html
2. Choose a dex file (the limitations on selecting multiple things is probably a bug in my HTML; I need to look that up.)
3. `onClickLoad` fires off when the button is pressed; it gets a list of files and then asks the browser to load them. Everything is asynchronous (callback-style) in javascript, so we need to bounce control over to `onFileReady` if we want to do something when the files are actually ready.
4. `ArrayFile` is just a wrapper of an array to make it look like some sort of standard file object.

Steps to run `mock-hello.html`
(You modified it, so you're probably more familiar with it.)
1. There's no real input right now; theoretically, it would be similar to `index.html`, but since the dex output is defined in `mock-hello.js` the execution starts right inside a script tag in `mock-hello.html`
    //--- main
    var myVM = new VM();
    var counter = 0;
    myVM.start(mock_hello_classes, "Ltest/HelloWorld;");

```
while(myVM.hasThreads()) {
  if (DEBUG) {
    terminal.appendDebug(counter+":\t"+myVM.getThreadState()+"\n", document.body);
    counter++;
  }
  myVM.clockTick();
}
```
1. We start off with the list of classes defined (only one in this case), and the name of the main class. This `VM.prototype.start` creates one thread if it is able. (We should probably be checking that return value eventually). Then, while the VM still has work to do (it has more threads to execute) we do stuff.

**Comment by etosch** [comment]
Okay, so the major bottleneck here is handling the conversion from CISC to RISC, right?

**Comment by jjfiv** [comment]
Yeah, that's the major piece in the middle missing.

**Comment by jjfiv** [comment]
See google doocument.
