### ISSUE TITLE
design how to represent threads

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#6]
We'll need a way of representing state for when an interrupt call is made. A given thread is represented by:

1)  value of the program counter
2) saved state of the current operation
3) ...

**Comment by jjfiv** [comment]
The "program counter" will need to have a reference to the current method, in some way or another, because there's no sense of a global pc. It is also part of a "stack frame". This is the key to designing threads.

A thread has a stack. A stack has frames. One for each method call. If they ever pop off the last one, that thread is done. When all threads are done, the VM terminates.

Each stack frame has N registers, known at the time of its creation, a reference to the method code itself, and a PC, which is an address/index into the "icode" array that defines our minimized set of opcodes.

**Comment by jjfiv** [comment]
Didn't mean to close, that button was closer :/
