### ISSUE TITLE
something funny happened on the GOTO FORUM

### ISSUE THREAD

**Issue by etosch** [jjfiv/dalvik-js#84]
goto/switch returning results, not setting result register - seems to be inconsistent with the model. explanation?

**Comment by jjfiv** [comment]
This is something you and I coded together, a very long time ago. :)

The result register is part of the actual VM spec; this is a part of our architecture - namely that if an icodeHandler returns nothing, it means the thread should increment the pc + 1; otherwise, it should increment the pc by the value returned. This is why `goto` and `switch` are returning values --- `if` should also return a value.

[Where we use the return value in Thread.js](https://github.com/jjfiv/dalvik-js/blob/c0ceede189b1c6df13f72f1514bd566cabe9f7d7/src/Thread.js#L106)

**Comment by etosch** [comment]
Got it!
