### ISSUE TITLE
Preliminary java/lang/Thread investigation

### ISSUE THREAD

**Issue by jjfiv** [jjfiv/dalvik-js#91]
Some reading material on [Threads in Java](http://en.wikibooks.org/wiki/Java_Programming/Threads_and_Runnables)

I was remembering incorrectly; `run()` is on a user subclass of `Runnable`, not of `Thread` so we'll need to do that.

We'll probably need hooks inside of `new-instance` to manufacture our own "synthetic" Thread objects, and we'll need hooks in invoke to catch all the methods...

I think maybe the best way to be doing these things is to have a flag on methods that let us know if the implementation is in javascript, and a function attached to it rather than icode to execute. This would allow our hacks within invoke to be small, and allow us to define objects elsewhere in javascript? Maybe this would just move the hacks to `new-instance` ...

So this is a design/find subtasks sort of challenge. Let me know if I can help.

**Comment by etosch** [comment]
I'm going to write some loosely connected statements to make sure I understand everything correctly. Since I promised to post within the hour, this is incomplete. I'll be editing, but I wanted to get it into the pipeline first (haw haw), since I'm not terribly effective at the superscalar thing (haw haw).

We have a notion of threads inside the VM. This is our Thread.js

Java has its own Thread object, which has certain features. When a user program creates a new Thread, this is done in a variety of ways. Regardless of implementation, the call to start the thread is located in the Runnable interface. 

This Java Thread class needs to be intercepted by our machine, much like calls to Class or Object. This will be implemented in a new file called invoke.js

I'm using the term "intercept" to denote the case where the invoke call would defer to the kinds things currently implemented as "hacks."  I chose the term because we are intercepting them before they get to the vanilla invoke handler.

We would need to ensure that the following subtasks (not listed in any particular order) are completed: 
- Define a predicate to determine whether something ought to be run as a thread on our VM. This could be something as simple as checking whether the method name is `run` and whether the method implements `Runnable`. While Threads can also be created by subclassing `Thread`, `Thread` also implements Runnable, so we're probably fine just checking for `Runnable`.
- All instance fields of the Thread are thread-local. This is already ensured by `new-instance`.  Static fields, as with any class, are shared amongst all Threads. We shouldn't need any special "hardware" for this.
- The tutorial page toggles between tasks using a random number of milliseconds for execution. Our current implementation has us doing a round-robin thing. I'm assuming that these are two different scheduling algos. Do we want to hold off on the random toggling for now? I kind of not-so-secretly want to implement cool scheduling algos, or I don't know, exponential backoff! But back on planet earth - Javascript's random number generator : do we need it? If so, is it good enough for our purposes? Also on this note, if the java.util.Random library is often used, do we want to be calling the javascript native random stuff or the java library? Also, shall we just ignore thread priority for now?
- The start instance method on java's Thread corresponds to adding our javascript Thread to the list of _threads on the VM.
- Add a `state` field to the Thread object, corresponding to the State inner class of Java's Thread. Write corresponding intercepts for [valueOf and values](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.State.html#valueOf%28java.lang.String%29)
- ThreadGroup can be handled by changing the VM's _threads data structure from an array to a tree
- interrupting a thread - will this even do anything for the round-robin scheduler? Behavior is determined by the scheduling algo.
- [activeCount](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#activeCount%28%29) should be straightforward. Consider maintaining an active count field in the VM that threads can modify, rather than querying threads, since the latter implementation could (a) cause inconsistency and (b) have high latency.
- [checkAccess](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#checkAccess%28%29) - is there a flag in the dex file that indicates this? Or do we infer from the tree in VM (e.g. I can access me, my parents can access me).
- [currentThread](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#currentThread%28%29) - this should be straightforward; pull from VM
- [dumpStack](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#dumpStack%28%29) - ignore
- [enumerate](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#enumerate%28java.lang.Thread[]%29) - straightforward
- everything related to stack traces - ignore
- [(get|set)ContextClassLoader](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#getContextClassLoader%28%29) - this harkens back to an earlier question I had about ClassLibrary. Are we going to ignore this or should we return a ClassLibrary? It seems analogous to ClassLibrary, but it looks like multiple ClassLoaders on the JVM might be permitted? Is this true for dalvik? 
- regarding ids -  I guess this means we need to add a uid to the Threads. This can be done with a generator/gensym-type-thing in the global.js file.
- [(get|set)UncaughtExceptionHandler](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#getUncaughtExceptionHandler%28%29) - not sure what opcodes this will call...
- [holdsLock](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Thread.html#holdsLock%28java.lang.Object%29) - will need to implement the monitor calls. This might not be sent to invoke.
- new states to add to our javascript Thread, will be called via getters and setters (we should be able to compress these into a single condition if we use RegExps wisely) : state, contextClassLoader/ClassLibrary?, id, name, priority, threadGroup, 

Do we handle deprecated functions?
Testing: 
Threads can be made in the following ways, so we ought to test each:
- Implementing `Runnable` as a named class
- Implementing `Runnable` as an anonymous class
- Sublassing `Thread` as a named class
- Subclassing `Thread` as an anonymous class?
  Each of these with each of the overloaded options (or maybe the maximal supersets)?

Are we going to want to implement Exceptions first?

**Comment by etosch** [comment]
So looking back on your original comment, it seems like there are two ways to proceed: do it ad hoc via intercepts (ie the above first pass commentary) or implement a kind of staging area. Do you think we can slip something between dexLoader and starting the VM to encapsulate thread behavior? We could hook it up to executing code by tagging stackframes with the thread responsible for their behavior.

**Comment by jjfiv** [comment]
Getting the current "VM Thread" from the current "VM Stackframe" should be easy.

My idea was kind of that we could create a class with a bunch of methods that would have "native" elements rather than "icode" elements, or something.

We can also clean up the invoke, like you described.

I honestly don't think it matters. We're still going to need to collect the hacks in one place -- whether that's in invoke or in some stage of loading the VM, I don't see either one being particularly easier.

**Comment by etosch** [comment]
So maybe a first pass in `invoke`:question: I hate to be that person, but maybe this problem would be best solved via test-driven development? :hammer: :hammer: :hamburger:

**Comment by etosch** [comment]
Anything thoughts on java.util.Random vs native javascript random?

**Comment by jjfiv** [comment]
java.util.Random isn't exactly on my list to implement. Wish-list 
feature, if we're done Saturday. Same goes for scheduling algorithms, 
unfortunately.

**Comment by jjfiv** [comment]
If by Test-Driven Development, you mean, create a java file and push it 
through, then absolutely. Doing any significant design without a test 
case to work toward would be irresponsible.

**Comment by etosch** [comment]
Okay, so for now we're going to ignore random instructions? throw an error? supply hard-coded instructions? use native javascript random?  I guess my vote goes towards saying that we won't support it.

Yeah I don't know if test-driven development is what they call it; I think it's a buzzword I heard somewhere and using my superior powers of reading comprehension I grafted some meaning onto it to serve my needs...

I'm off to reading papers now. Will check back in in a few hours. My goal before the end of the night is to push a comprehensive and incremental tester (the comprehensive part will package all the thread tests as a single file. the incremental part will be the individual tests that test a single feature.)

Barring any issues with power, ping me for an update around 10pm?

**Comment by jjfiv** [comment]
I didn't read all of your investigation; I'll look into what kind of 
randomness you're talking about because we don't seem to be on the same 
page. There is no "random" instruction in Dalvik, so if we need it for a 
library call, we can use javascripts, if necessary.

**Comment by jjfiv** [comment]
Ah, I see, random is totally my fault. Let's just come up with examples that avoid randomness for now. Getting something working with Threads is first; getting them scheduled better is after that.

**Comment by etosch** [comment]
:+1:

**Comment by jjfiv** [comment]
Is this closed now that subissues have been created?

**Comment by etosch** [comment]
Not yet; I need to review the thread and make sure all comments/concerns
are covered by the new issues. I'll close after addressing these.

On Wed, Oct 31, 2012 at 12:26 PM, John Foley notifications@github.comwrote:

> Is this closed now that subissues have been created?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jjfiv/dalvik-js/issues/91#issuecomment-9951510.

## 

Emma Tosch
Graduate Research Assistant, Computational Intelligence Lab, Hampshire
College
MS/PhD student, University of Massachusetts, Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by jjfiv** [comment]
A lot of issues have been resolved on Threads; goals are now limited to a better scheduler for Thread.sleep Issue #100
